---
version: 2.7.2
slug: mariadb-nextcloud
name: MariaDB Nextcloud
description: A SQL database server
url: https://github.com/home-assistant/addons/tree/master/mariadb
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
backup_post: unlock-tables-for-backup
backup_pre: lock-tables-for-backup
image: homeassistant/{arch}-addon-mariadb
init: false
options:
  databases:
    - nextcloud
  logins:
    - password: null
      username: service
  rights:
    - database: nextcloud
      username: service
ports:
  3306/tcp: 3307
schema:
  databases:
    - str
  logins:
    - username: str
      password: password
  rights:
    - database: str
      privileges:
        - "list(ALTER|CREATE|CREATE ROUTINE|CREATE TEMPORARY TABLES|\
          CREATE VIEW|DELETE|DELETE HISTORY|DROP|EVENT|GRANT OPTION|INDEX|\
          INSERT|LOCK TABLES|SELECT|SHOW VIEW|TRIGGER|UPDATE)?"
      username: str
  mariadb_server_args:
    - str?
services:
  - mysql:provide
startup: system
timeout: 300
